### ISSUE TITLE
Textwidth gives bad result on multiline strings

### ISSUE THREAD

**Issue by dmrvb** [twinbasic/twinbasic#1824]
**Describe the bug**
Textwidth gives a bad result on multiline strings

it returns the total length of all lines added together, it should return the longest line

**To Reproduce**

Private Sub Command1_Click()

Dim st As String
Dim tl As Long

st = "123456789"
tl = Me.TextWidth(st)
Debug.Print tl

st = "123456789" & vbCr & "123"
tl = Me.TextWidth(st)
Debug.Print tl

End Sub

second result is bigger than the first, should be the same.

**Desktop (please complete the following information):**
 - OS: [e.g. Win 11]
 - twinBASIC compiler version: almost the latest version, they are coming very quickly just now

**Comment by dmrvb** [comment]
and textheight is correspondingly wrong.

**Comment by WaynePhillipsEA** [comment]
Only `vbCrLf` is supported for this in currently releases.   There is a todo notice in the implementation for TextWidth mentioning it.   I'll try to get it supported for the upcoming release

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 502.  Thanks

**Comment by dmrvb** [comment]
Possible reopen, I think there is still something wrong here but I need to investigate more. (a bit later today)
Note that I am defining constants to put into my strings: 

Public Const vbCr2 As String = vbCr & vbCr
Public Const vbCrLf2 As String = vbCrLf & vbCrLf

and I THINK these are still not getting handled correctly (I THINK width is ok but height is wrong)

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 503, thanks
