### ISSUE TITLE
Toolbar links to wrong Image List

### ISSUE THREAD

**Issue by dmrvb** [twinbasic/twinbasic#2034]
**Describe the bug**
**_Sometimes_** the Toolbar control displays images from an incorrect image list. This is usually an imagelist having the correct (duplicate) name but located on a different form. For example I have "Imagelist1 on several forms.
I **_think_** that sometimes it finds some sort of default or system imagelist.

**To Reproduce**
I will attempt to create a test prog if this bug is not easy to track down.
**Expected behavior**
Toolbar should link to the imagelist on the same form.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 11]
 - twinBASIC compiler version [678 and some/all previous versions]

**Comment by liuzj01** [comment]
I have been encountering this error while using the built-in ImageList in the IDE. I have checked the images and there are no issues with the code. How can I solve this problem?

I have been using the built-in treeview and imagelist in the IDE, but this error persists. I have checked the code and settings and found no issues, and the code is working properly in VB6.
I uploaded two pictures, I don't know if you can see them.

![Image](https://github.com/user-attachments/assets/3635e746-3243-4c27-be51-76fdacabaf1d)
![Image](https://github.com/user-attachments/assets/f8202af7-8197-4f21-bd6b-7676ed3f305a)

**Comment by dmrvb** [comment]
I still have this bug.
My initial go at creating a simple test prog have failed to replicate this issue.
I can try to cut down my big prog to isolate the bug but this is potentially a big job.
I have one form which picks up the imagelist from a different form, and one form which looks to use a system imagelist rather then my imagelist.

**Comment by WaynePhillipsEA** [comment]
I'm keen to get this fixed, but need to be able to reproduce it

**Comment by dmrvb** [comment]
Yes, this is possibly the only significant bug left for my stuff. I will try to pin it down.

**Comment by dmrvb** [comment]
>>>>>>>>>>>>>>>>Here is a Testprog<<<<<<<<<<<<<<<<<<<<<<<<<

click the showform button and obseve that the new form uses the imagelist from Form1 rather than its own imagelist.
Notes:
1 I was unable to replicate this bug by creating a new form, but can by cutting down an existing form.
2 I have removed all code from the form.
3 I have not removed the controls. If the bug is not obvious and you want me to sequentially remove controls then let me know.

[ToolbarImageBug4.zip](https://github.com/user-attachments/files/21075624/ToolbarImageBug4.zip)

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 849, thanks

**Comment by dmrvb** [comment]
I need to reopen this one.
The "imagelist from wrong form" is fixed, but the similar issue where a system imagelist is used rather than my imagelist is still present.
I had hoped and assumed these were the same issue.
I will try to pin this one down but it might be difficult (the offending form has third party controls and loads of dependencies).

**Comment by dmrvb** [comment]
I have a second form showing this issue. I use this same form in three projects.
In two cases it gets some sort of system image list (I think). In the third case it gets the wrong image list again (correct name but wrong form). It's likely going to be very difficult to reduce this to a simple test prog.
Could you have missed anything in your recent fix of this one???  

Image shows the wrong images in a toolbar. Pretty sure these are not from any of my imagelists.

<img width="1054" height="686" alt="Image" src="https://github.com/user-attachments/assets/b8d87507-f7b9-4b5d-8275-1ea2713fa613" />

**Comment by dmrvb** [comment]
Here is a testprog. 
In sub main I load Form2 which contains an imagelist1. I then load a form "SSsave" which also contains an Imagelist1 but when I show this form the toolbar has taken the images from the imagelist on Form2.

SSsave is an existing form with all code removed. If I create a new form (Form3) inVB6 also with an imagelist and toolbar then this does not show the bug.

[ImBug4.zip](https://github.com/user-attachments/files/21317756/ImBug4.zip)

**Comment by dmrvb** [comment]
I am still seeing this bug in all recent versions (eg up to 907). In particular I get the issue where my toolbar gets images from some sort of system imagelist rather than my imagelist (as shown above). Can't easily replicate this in a simple test prog, though the "wrong image list" bug in the test prog above is still present.
